KS-4-4 print what to train today
oileee/KotlinSprint pull request #19
Opened 2024-09-26 21:58 UTC by oileee

2024-09-27 15:04 UTC, ievetrovdev requested changes
Слишком длинная строка (больше 120 символов), как правило в крупных и средних компаниях есть системы проверяющие код, которые не пропустят такое форматирование (например [Detekt](https://detekt.dev/docs/rules/formatting/#maximumlinelength)). Давай добавим переносы

2024-09-27 15:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task4.kt
> +    println("Упражнения для рук: ${(dayOfTraining % 2) == 1}\nУпражнения для ног: ${(dayOfTraining % 2) == 0}\nУпражнения для спины: ${(dayOfTraining % 2) == 0}\nУпражнения для пресса: ${(dayOfTraini
Правильный ход мыслей, но лучше кое что оптимизировать)
Не соблюдается принцип [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

Лучше вынести нахождение четности (только четности) числа в отдельный флаг и применять его уже при выводе напрямую или с отрицанием (инвертируя).

Более распространенная практика находить четность числа и сравнивать именно с 0.

2024-09-27 15:04 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task4.kt
> +    println("Упражнения для рук: ${(dayOfTraining % 2) == 1}\nУпражнения для ног: ${(dayOfTraining % 2) == 0}\nУпражнения для спины: ${(dayOfTraining % 2) == 0}\nУпражнения для пресса: ${(dayOfTraini
Boolean переменные принято называть isSomeSituation (не обязательно, но так код легче читается). Давай назовем isEvenDay

2024-09-27 22:55 UTC, oileee commented on src/main/kotlin/lesson_4/lesson4_task4.kt
> +    println("Упражнения для рук: ${(dayOfTraining % 2) == 1}\nУпражнения для ног: ${(dayOfTraining % 2) == 0}\nУпражнения для спины: ${(dayOfTraining % 2) == 0}\nУпражнения для пресса: ${(dayOfTraini
ага, ясно

2024-09-27 23:03 UTC, oileee commented on src/main/kotlin/lesson_4/lesson4_task4.kt
> +    println("Упражнения для рук: ${(dayOfTraining % 2) == 1}\nУпражнения для ног: ${(dayOfTraining % 2) == 0}\nУпражнения для спины: ${(dayOfTraining % 2) == 0}\nУпражнения для пресса: ${(dayOfTraini
Спасибо! Мне нравится узнавать тонкости)

2024-09-28 16:33 UTC, ievetrovdev approved these changes
Хорошее решение!

2024-10-11 06:33 UTC, merged